#!/bin/bash

sudo apt-get install sed wget cvs subversion git-core coreutils
sudo apt-get install unzip texi2html texinfo libsdl1.2-dev docbook-utils gawk 
sudo apt-get install python-pysqlite2 diffstat help2man make gcc build-essential
sudo apt-get install g++ desktop-file-utils chrpath libgl1-mesa-dev 
sudo apt-get install libglu1-mesa-dev mercurial autoconf automake groff libtool xterm
